/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("net.risesoft.y9.java-conventions")
    id("net.risesoft.y9.java-conventions")
    id("net.risesoft.y9.lombok")
    id("net.risesoft.y9.docker")
    id("war")
    alias(libs.plugins.org.springframework.boot)
}

dependencies {
    api(project(":risenet-y9boot-support-webmail"))
    api(y9libs.net.risesoft.risenet.y9boot.starter.sso.oauth2.resource)
    api(y9libs.net.risesoft.risenet.y9boot.common.nacos)
    api(y9libs.org.apache.commons.commons.pool2)
    providedCompile(libs.org.springframework.boot.spring.boot.starter.tomcat)
}

description = "risenet-y9boot-webapp-webmail"
