/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("net.risesoft.y9.java-conventions")
    id("net.risesoft.y9.lombok")
}

dependencies {
    api(y9libs.net.risesoft.risenet.y9boot.starter.openfeign)
    api(y9libs.net.risesoft.risenet.y9boot.api.interface.email)
    compileOnly(libs.jakarta.servlet.jakarta.servlet.api)
}

description = "risenet-y9boot-api-feignclient-webmail"
