management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8080
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
            force-request: true
            force-response: true
        context-path: /webmail
    tomcat:
        uri-encoding: UTF-8
spring:
    application:
        name: webmail
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
            - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
            - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    cloud:
        nacos:
            config:
                enabled: false
                group: DEFAULT_GROUP
                namespace: dev
                server-addr: https://dev.youshengyun.com:443
                username: nacos
                password: nacos@2022
            discovery:
                enabled: false
    config:
        import:
            - optional:nacos:webmail.yml
            #- optional:nacos:test01.yml?group=group_02
            #- optional:nacos:test02.yml?group=group_03&refreshEnabled=false
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        name: y9PublicDS
        generate-unique-name: false
        druid:
            y9-public:
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/y9_public?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false&allowPublicKeyRetrieval=true
                username: root
                #driver-class-name: oracle.jdbc.OracleDriver
                #url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
                #username: Y9_PUBLIC
                password: '111111'
                initialSize: 1
                maxActive: 20
                maxPoolPreparedStatementPerConnectionSize: 100
                maxWait: 60000
                minEvictableIdleTimeMillis: 300000
                minIdle: 1
                poolPreparedStatements: true
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 60000
                useGlobalDataSourceStat: true
                validationQuery: SELECT 1 FROM DUAL
            webmail:
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/james?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false&allowPublicKeyRetrieval=true
                username: root
                password: 111111
                initialSize: 1
                maxActive: 20
                maxPoolPreparedStatementPerConnectionSize: 100
                maxWait: 60000
                minEvictableIdleTimeMillis: 300000
                minIdle: 1
                poolPreparedStatements: true
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 60000
                useGlobalDataSourceStat: true
                validationQuery: SELECT 1 FROM DUAL
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 2000
                wall:
                    config:
                        drop-table-allow: false
                    enabled: true
            stat-view-servlet:
                enabled: true
                login-password: admin
                login-username: admin
                reset-enable: false
                url-pattern: /druid/*
            web-stat-filter:
                enabled: true
                exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/static/*'
                url-pattern: /*
    jpa:
        hibernate:
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
        properties:
            hibernate:
                cache:
                    use_query_cache: false
                    use_second_level_cache: false
                dialect: org.hibernate.dialect.MySQL8Dialect
                hbm2ddl:
                    auto: update
                jdbc:
                    batch_size: 100
                show_sql: true
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-commit-interval: 1000
            enable-auto-commit: true
            group-id: y9webmail-server
    main:
        allow-bean-definition-overriding: true
        allow-circular-references: true
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    redis:
        database: 8
        host: localhost
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1
                min-idle: 0
                shutdown-timeout: 100ms
        password: y9i-83204585
        port: 6379
        ssl: false
        timeout: 10000
    servlet:
        multipart:
            max-file-size: 1024MB
            max-request-size: 1000MB
y9:
    systemCnName: '电子邮件'
    systemName: webmail
    internalIp: 192.168.x.x,10.0.x.x,172.20.x.x
    app:
        webmail:
            imapHost: imap.youshengyun.com
            imapPort: 143
            smtpHost: smtp.youshengyun.com
            smtpPort: 25
            jmx-host: 192.168.0.110
            jmxPort: 9999
            host: youshengyun.com
    service:
        org:
            directUrl: http://localhost:7055
    common:
        default-password: 111111
        kafkaEnabled: true
        orgBaseUrl: http://127.0.0.1:7055/platform
        emailBaseUrl: http://127.0.0.1:7056/email
        webmailBaseUrl: http://127.0.0.1:7056/webmail
        jodconverterBaseUrl: http://newoa.nanhai.gov.cn/jodconverter
        logBaseUrl: http://localhost:7056/log
        userOnlineBaseUrl: http://localhost:7056/userOnline
    feature:
        file:
            rest:
                fileManagerUrl: http://127.0.0.1:7055/fileManager
            base64FileName: false
            encryptionFileContent: false
            #privateKey:
            #publicKey:
            ftp:
                host: 192.168.3.5
                port: 21
                username: y9admin
                password: '111111'
                blockWhenExhausted: true
                bufferSize: 10240
                connectTimeOut: 50000
                controlEncoding: UTF-8
                dataTimeout: 1200000
                fileType: 2
                maxIdle: 10
                maxTotal: 50
                minIdle: 2
                maxWaitMillis: 5400000
                testOnBorrow: true
                testOnCreate: true
                testOnReturn: true
                testWhileIdle: true
                useEPSVwithIPv4: false
                passiveMode: true
        jpa:
            packagesToScanEntityPublic: net.risesoft.y9public.entity
            packagesToScanEntityTenant: net.risesoft.entity
            packagesToScanEntityDedicated: net.risesoft.james.entity
            packagesToScanRepositoryPublic: net.risesoft.y9public.repository
            packagesToScanRepositoryTenant: net.risesoft.repository
            packagesToScanRepositoryDedicated: net.risesoft.james.repository
        listener:
            kafka:
                enabled: true
        log:
            enabled: true
            # kafka, api
            logSaveTarget: kafka
        session:
            redis:
                enabled: true
                maxInactiveIntervalInSeconds: 3600
        security:
            cors:
                allowCredentials: true
                allowedOriginPatterns:
                    - https://*.youshengyun.com
                    - http://*.youshengyun.com
                    - http://localhost:7056
                    - http://localhost:8080
                    - http://localhost:8081
                    - http://localhost:7070
                    - http://127.0.0.1:7055
                    - http://127.0.0.1:7056
                    - http://127.0.0.1:17055
            xss:
                enabled: false
        oauth2:
            resource:
                enabled: true
                saveLogMessage: false
                saveOnlineMessage: false
                allowFormEncodedBodyParameter: true
                allowUriQueryParameter: true
                protectedUrlPatterns: /api/*
                opaque:
                    client-id: clientid
                    client-secret: secret
                    introspection-uri: http://localhost:7055/sso/oauth2.0/introspect
                    profile-uri: http://localhost:7055/sso/oauth2.0/profile
