spring:
    cloud:
        nacos:
            config:
                enabled: true
                namespace: ${NACOS_NAMESPACE:dev}
                group: DEFAULT_GROUP
                server-addr: ${NACOS_SERVER_ADDR:https://dev.youshengyun.com:443}
                username: ${NACOS_USERNAME:nacos}
                password: ${NACOS_PASSWORD:111111}
    config:
        import:
            - optional:nacos:webmail.yml