/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("net.risesoft.y9.java-conventions")
    id("net.risesoft.y9.lombok")
}

dependencies {
    api(y9libs.net.risesoft.risenet.y9boot.common.model)
    api(y9libs.org.springframework.spring.web)
    api(y9libs.org.springframework.boot.spring.boot.starter.validation)
}

description = "risenet-y9boot-api-interface-webmail"
